routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'Auth\LoginController@showLoginForm');
Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('admin/logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['auth', 'role:root-admin']], function () {
        Route::resource('admins', 'Admin\AdminController');
        Route::resource('roles', 'Admin\RoleController');
        Route::resource('menus', 'Admin\MenuController');
    });
    Route::group(['middleware' => ['auth', 'role:root-admin|admin']], function () {
        Route::resource('menus', 'Admin\MenuController')->except('destroy', 'edit', 'update');
    });
    Route::get('/', 'Admin\HomeController@home')->name('admin-home');
    Route::post('/menus/addsidebar/{id}', 'Admin\MenuController@addSidebar')->name('menus.sidebar');
    Route::post('/menus/removesidebar/{id}', 'Admin\MenuController@removeSidebar')->name('menus.removesidebar');
    Route::post('/menus/addcolumn', 'Admin\MenuController@addFields')->name('menus.addcolumn');
    Route::get('tables/{table}', 'Admin\TableController@index')->name('tables.index');
    Route::get('tables/create/{table}', 'Admin\TableController@create')->name('tables.create');
    Route::post('tables/store', 'Admin\TableController@store')->name('tables.store');
    Route::get('tables/show/{column}/{type}', 'Admin\TableController@show')->name('tables.show');
    Route::get('tables/{table}/{column}', 'Admin\TableController@edit')->name('tables.edit');
    Route::post('tables/update/{column}', 'Admin\TableController@update')->name('tables.updated');
    Route::post('tables/delete/{table}/{column}', 'Admin\TableController@destroy')->name('tables.destroy');
});

Route::prefix('admin')->group(function () {
    Route::resource('car', 'Admin\CarController');
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Menu extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $guarded = ['id'];
    public $table = 'menus';
    public $fillable = [
        'name',
        'icon',
        'order_by'
    ];
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MenuRequest;
use Illuminate\Http\Request;
use App\Models\Menu;
use App\CreateModel;
use Auth;

class MenuController extends Controller
{
    public function index()
    {
        if (Auth::user()->hasRole('root-admin')) {
            $menus = Menu::whereNull('deleted_at')->paginate(10);
        }else{
            $menus = Menu::whereNotIn('id', ['1', '2'])->whereNull('deleted_at')->paginate(10);
        }
        
        return view('admin.menu.index', compact('menus'));
    }

    public function create()
    {
        return view('admin.menu.create');
    }

    public function store(MenuRequest $request)
    {
        $menu = Menu::create($request->all());
        // $createMenu = CreateModel::createDashboard($request->name);
        
        return redirect(route('menus.index'))
            ->with('success', 'Menu saved successfully.');
    }

    public function show($id)
    {
        $menu = Menu::findOrFail($id);

        return view('admin.menu.show', compact('menu'));
    }

    public function edit($id)
    {
        $menu = Menu::findOrFail($id);

        return view('admin.menu.edit', compact('menu'));
    }

    public function update(MenuRequest $request, $id)
    {
        $menu = Menu::findOrFail($id);
        $menu->update($request->all());

        return redirect(route('menus.index'))
            ->with('success', 'Menu updated successfully.');
    }

    public function destroy($id)
    {
        $menu = Menu::findOrFail($id);
        $remove_menu = CreateModel::removeDashboard($menu->name);
        Menu::destroy($id);
        
        return redirect()->back()
            ->with('danger', 'Menu deleted successfully');
    }

    public function addSidebar($id)
    {
        $menu = Menu::findOrFail($id);
        $model = base_path('app/Models/').ucfirst($menu->name).".php";
        if (!file_exists($model)) {
            $createMenu = CreateModel::createDashboard($menu->name);
        }
        Menu::where('id', $menu->id)->update([
            'sidebar' => '1'
        ]);
        return redirect()->back();
    }

    public function removeSidebar($id)
    {
        $menu = Menu::where('id', $id)->update([
            'sidebar' => '0'
        ]);
        return redirect()->back();
    }
}

resources/views/admin/menu/create.blade.php
@extends('admin.home')

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/css/fontawesome-iconpicker.css" integrity="sha256-KC2XUWlJX7EuWPF02ZakG9K7ny3Y9AYDfmdnQD/pLlU=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/css/fontawesome-iconpicker.min.css" integrity="sha256-yExEWA6b/bqs3FXxQy03aOWIFtx9QEVnHZ/EwemRLbc=" crossorigin="anonymous" />
@stop

@section('content_header')
    <div class="text-center">
        <label for="menu">Create Menu</label>
    </div>
@stop

@section('content')
    @include('layouts.errors')
    <div class="panel-body">
        {!! Form::open(['route' => 'menus.store', 'method' => 'post']) !!}
            <div class="form-group col-sm-4 {{ $errors->has('name') ? 'has-error' : '' }}">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
                @if($errors->has('name'))
                    <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>
            <div class="form-group col-sm-4">
                {!! Form::label('icon', 'Icon') !!}
                <div class="input-group">
                    <input data-placement="bottomRight" class="form-control icon" value="fas fa-archive"
                    type="text" name="icon" />
                    <span class="input-group-addon"></span>
                </div>
            </div>
            <div class="form-group col-sm-4">
                {!! Form::label('order_by', 'Order By') !!}
                {!! Form::text('order_by', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group col-sm-12">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{!! route('menus.index') !!}" class="btn btn-default">Cancel</a>
        {!! Form::close() !!}
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.js" integrity="sha256-sAlwRjlYvlekTLgTnPQK/oO1b+zc2Phz6cbLRVXWfyI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.min.js" integrity="sha256-QvBM3HnWsvcCWqpqHZrtoefjB8t2qPNzdSDNyaSNH5Q=" crossorigin="anonymous"></script>
    <script>
        $('.icon').iconpicker();
    </script>
@stop

resources/views/admin/menu/edit.blade.php
@extends('admin.home')

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/css/fontawesome-iconpicker.css" integrity="sha256-KC2XUWlJX7EuWPF02ZakG9K7ny3Y9AYDfmdnQD/pLlU=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/css/fontawesome-iconpicker.min.css" integrity="sha256-yExEWA6b/bqs3FXxQy03aOWIFtx9QEVnHZ/EwemRLbc=" crossorigin="anonymous" />
@stop

@section('content_header')
    <div class="text-center">
        <label for="menu">Create Menu</label>
    </div>
@stop

@section('content')
    @include('layouts.errors')
    <div class="panel-body">
        {!! Form::open(['route' => ['menus.update', $menu->id], 'method' => 'put']) !!}
            <div class="form-group col-sm-4">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', $menu->name, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group col-sm-4">
                {!! Form::label('icon', 'Icon') !!}
                <div class="input-group">
                <input data-placement="bottomRight" class="form-control icon" value="{{ $menu->icon }}"
                    type="text" name="icon" />
                    <span class="input-group-addon"></span>
                </div>
            </div>
            <div class="form-group col-sm-4">
                {!! Form::label('order_by', 'Order By') !!}
                {!! Form::text('order_by', $menu->order_by, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group col-sm-12">
                {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
            <a href="{!! route('menus.index') !!}" class="btn btn-default">Cancel</a>
        {!! Form::close() !!}
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.js" integrity="sha256-sAlwRjlYvlekTLgTnPQK/oO1b+zc2Phz6cbLRVXWfyI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.min.js" integrity="sha256-QvBM3HnWsvcCWqpqHZrtoefjB8t2qPNzdSDNyaSNH5Q=" crossorigin="anonymous"></script>
    <script>
        $('.icon').iconpicker();
    </script>
@stop

resources/views/admin/menu/index.blade.php
@extends('admin.home')

@section('css')

@stop

@section('content_header')
    <ol class="breadcrumb pull-right">
        <li class="breadcrumb-item"><a class="btn btn-primary" href="{!! route('menus.create') !!}" style="color:white">Add New</a></li>
    </ol>
    <br><br>
@stop

@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block" style="margin-top: 3%;">
            <button type="button" class="close" data-dismiss="alert">×</button>	
                <strong>{{ $message }}</strong>
        </div>
    @endif
    @if ($message = Session::get('danger'))
        <div class="alert alert-danger alert-block" style="margin-top: 3%;">
            <button type="button" class="close" data-dismiss="alert">×</button>	
                <strong>{{ $message }}</strong>
        </div>
    @endif
    <div class="panel panel-inverse" data-sortable-id="index-1">
        <div class="panel-heading">
            <label class="panel-title">&nbsp;Menus</label>
        </div>
        <div class="panel-body">
            <table class="table display table-striped table-bordered dt-responsive" >
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Icon</th>
                        <th>Icon Type</th>
                        <th>Side Bar</th>
                        <th>Order By</th>
                        <th>Actions</th>
                        <th>Add To Sidebar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($menus as $menu)
                        <tr>
                            <td>{!! $menu->id !!}</td>
                            <td>{!! $menu->name !!}</td>
                            <td><i class="{!! $menu->icon !!}"></i></td>
                            <td>{!! $menu->icon !!}</td>
                            <td>
                                @if($menu->sidebar != '0')
                                    <label class="badge btn-success">True</label>
                                @else 
                                    <label class="badge btn-primary">False</label>
                                @endif
                            </td>
                            <td>{!! $menu->order_by !!}</td>
                            <td>
                                {!! Form::open(['route' => ['menus.destroy', $menu->id], 'method' => 'DELETE', 'class' => 'form-delete', 'id' => 'form']) !!}
                                    <div class="btn-group">
                                        <a href="{!! route('menus.show', $menu->id) !!}" class='btn btn-success btn-xs'><i class="fa fa-eye"></i></a>
                                        @if(Auth::user()->hasRole('root-admin'))
                                            <a href="{!! route('menus.edit', $menu->id) !!}" class='btn btn-info btn-xs'><i class="fa fa-edit"></i></a>
                                            {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure DELETE?')"]) !!}
                                        @endif
                                    </div>
                                {!! Form::close() !!}
                            </td>
                            <td>
                                @if($menu->sidebar == '0')
                                    {!! Form::open(['route' => ['menus.sidebar', $menu->id], 'method' => 'POST']) !!}
                                        {!! Form::button('<i class="fa fa-sliders-h"></i>', ['type' => 'submit', 'class' => 'btn btn-primary btn-xs', 'onclick' => "return confirm('Add menu to Sidebar?')"]) !!}
                                    {!! Form::close() !!}
                                @else 
                                    {!! Form::open(['route' => ['menus.removesidebar', $menu->id], 'method' => 'POST']) !!}
                                        {!! Form::button('<i class="fa fa-ban"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure REMOVE  menu to Sidebar?')"]) !!}
                                    {!! Form::close() !!}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="text-center">
        {!! $menus->links() !!}
    </div>
@stop

resources/views/admin/menu/show.blade.php
@extends('admin.home')

@section('content_header')

@stop

@section('content')
<div class="panel-body">
    <div class="col-sm-6">
        <table class="table table-striped table-bordered">
            <!-- Id Field -->
            <tr>
                <th>{!! Form::label('id', 'Id:') !!}</th>
                <td>{!! $menu->id !!}</td>
            </tr>
            <!-- Name Field -->
            <tr>
                <th>{!! Form::label('name', 'Name:') !!}</th>
                <td>{!! $menu->name !!}</td>
            </tr>
            <tr>
                <th>{!! Form::label('icon', 'Icon:') !!}</th>
                <td><i class="{!! $menu->icon !!}"></i></td>
            </tr>
            <tr>
                <th>{!! Form::label('icon name', 'Icon Name:') !!}</th>
                <td>{!! $menu->icon !!}</td>
            </tr>
            <tr>
                <th>{!! Form::label('order_by', 'Order By') !!}</th>
                <td>{!! $menu->order_by !!}</td>
            </tr>
        </table>
        <a href="{!! route('menus.index') !!}" class="btn btn-primary">Back</a>
    </div>
</div>
@stop