routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'Auth\LoginController@showLoginForm');
Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('admin/logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['auth', 'role:root-admin']], function () {
        Route::resource('admins', 'Admin\AdminController');
        Route::resource('roles', 'Admin\RoleController');
        Route::resource('menus', 'Admin\MenuController');
    });
    Route::group(['middleware' => ['auth', 'role:root-admin|admin']], function () {
        Route::resource('menus', 'Admin\MenuController')->except('destroy', 'edit', 'update');
    });
    Route::get('/', 'Admin\HomeController@home')->name('admin-home');
    Route::post('/menus/addsidebar/{id}', 'Admin\MenuController@addSidebar')->name('menus.sidebar');
    Route::post('/menus/removesidebar/{id}', 'Admin\MenuController@removeSidebar')->name('menus.removesidebar');
    Route::post('/menus/addcolumn', 'Admin\MenuController@addFields')->name('menus.addcolumn');
    Route::get('tables/{table}', 'Admin\TableController@index')->name('tables.index');
    Route::get('tables/create/{table}', 'Admin\TableController@create')->name('tables.create');
    Route::post('tables/store', 'Admin\TableController@store')->name('tables.store');
    Route::get('tables/show/{column}/{type}', 'Admin\TableController@show')->name('tables.show');
    Route::get('tables/{table}/{column}', 'Admin\TableController@edit')->name('tables.edit');
    Route::post('tables/update/{column}', 'Admin\TableController@update')->name('tables.updated');
    Route::post('tables/delete/{table}/{column}', 'Admin\TableController@destroy')->name('tables.destroy');
});

Route::prefix('admin')->group(function () {
    Route::resource('car', 'Admin\CarController');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware(['role:root-admin']);
    }
    public function index()
    {
        $roles = Role::paginate(10);
        
        return view('admin.role.index', compact('roles'));
    }
    public function create()
    {
        return view('admin.role.create');
    }

    public function store(Request $request)
    {
        $role = Role::create($request->all());

        return redirect()->route('roles.index')
            ->with('success', 'Role created successfully.');
    }

    public function show($id)
    {
        $role = Role::findOrFail($id);

        return view('admin.role.show', compact('role'));
    }

    public function edit($id)
    {
        $role = Role::findOrFail($id);

        return view('admin.role.edit', compact('role'));
    }

    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $role->update($request->all());

        return redirect()->route('roles.index')
            ->with('success', 'Role created successfully.');
    }

    public function destroy($id)
    {
        return view('admin.role.index');
    }
}

resources/views/admin/role/create.blade.php
@extends('admin.home')

@section('content_header')
    <div class="text-center">
        <label for="role">Create Role</label>
    </div>
@stop

@section('content')
<div class="panel-body">
    {!! Form::open(['route' => 'roles.store', 'method' => 'post']) !!}
        <div class="form-group col-sm-4">
            {!! Form::label('name', 'Name') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group col-sm-12">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('roles.index') !!}" class="btn btn-default">Cancel</a>
    {!! Form::close() !!}
</div>
@stop

resources/views/admin/role/edit.blade.php
@extends('admin.home')

@section('content_header')
    <div class="text-center">
        <label for="role">Update Role</label>
    </div>
@stop

@section('content')
<div class="panel-body">
    {!! Form::open(['route' => ['roles.update', $role->id], 'method' => 'put']) !!}
        <div class="form-group col-sm-4">
            {!! Form::label('name', 'Name') !!}
            {!! Form::text('name', $role->name, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group col-sm-12">
            {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('roles.index') !!}" class="btn btn-default">Cancel</a>
    {!! Form::close() !!}
</div>
@stop

resources/views/admin/role/index.blade.php
@extends('admin.home')

@section('content_header')
    <ol class="breadcrumb pull-right">
        <li class="breadcrumb-item"><a class="btn btn-primary" href="{!! route('roles.create') !!}" style="color:white">Add New</a></li>
    </ol>
    <br>
@stop

@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block" style="margin-top: 3%;">
            <button type="button" class="close" data-dismiss="alert">×</button>	
                <strong>{{ $message }}</strong>
        </div>
    @endif
    <label for="roles" class="pull-left">&nbsp;Roles</label>
    <table class="table display table-striped table-bordered dt-responsive" >
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($roles as $key=>$role)
                <tr>
                    <td>{!! $role->id !!}</td>
                    <td>{!! $role->name !!}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{!! route('roles.show', [$role->id]) !!}" class='btn btn-success btn-xs'><i class="fa fa-eye"></i></a>
                            <a href="{!! route('roles.edit', [$role->id]) !!}" class='btn btn-info btn-xs'><i class="fa fa-edit"></i></a>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@stop

resources/views/admin/role/show.blade.php
@extends('admin.home')

@section('content_header')

@stop

@section('content')
<div class="panel-body">
    <div class="col-sm-6">
        <table class="table table-striped table-bordered">
            <!-- Id Field -->
            <tr>
                <th>{!! Form::label('id', 'Id:') !!}</th>
                <td>{!! $role->id !!}</td>
            </tr>
            <!-- Name Field -->
            <tr>
                <th>{!! Form::label('name', 'Name:') !!}</th>
                <td>{!! $role->name !!}</td>
            </tr>
        </table>
        <a href="{!! route('roles.index') !!}" class="btn btn-primary">Back</a>
    </div>
</div>
@stop