routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'Auth\LoginController@showLoginForm');
Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('admin/logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['auth', 'role:root-admin']], function () {
        Route::resource('admins', 'Admin\AdminController');
        Route::resource('roles', 'Admin\RoleController');
        Route::resource('menus', 'Admin\MenuController');
    });
    Route::group(['middleware' => ['auth', 'role:root-admin|admin']], function () {
        Route::resource('menus', 'Admin\MenuController')->except('destroy', 'edit', 'update');
    });
    Route::get('/', 'Admin\HomeController@home')->name('admin-home');
    Route::post('/menus/addsidebar/{id}', 'Admin\MenuController@addSidebar')->name('menus.sidebar');
    Route::post('/menus/removesidebar/{id}', 'Admin\MenuController@removeSidebar')->name('menus.removesidebar');
    Route::post('/menus/addcolumn', 'Admin\MenuController@addFields')->name('menus.addcolumn');
    Route::get('tables/{table}', 'Admin\TableController@index')->name('tables.index');
    Route::get('tables/create/{table}', 'Admin\TableController@create')->name('tables.create');
    Route::post('tables/store', 'Admin\TableController@store')->name('tables.store');
    Route::get('tables/show/{column}/{type}', 'Admin\TableController@show')->name('tables.show');
    Route::get('tables/{table}/{column}', 'Admin\TableController@edit')->name('tables.edit');
    Route::post('tables/update/{column}', 'Admin\TableController@update')->name('tables.updated');
    Route::post('tables/delete/{table}/{column}', 'Admin\TableController@destroy')->name('tables.destroy');
});

Route::prefix('admin')->group(function () {
    Route::resource('car', 'Admin\CarController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Model;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/user/create.blade.php
@extends('admin.home')

@section('content_header')
    <div class="text-center">
        <label for="admin-users">Create Admin User</label>
    </div>
@stop

@section('content')
    @include('layouts.errors')
    <div class="panel-body">
        {!! Form::open(['route' =>'admins.store', 'method' => 'post']) !!}
            <div class="form-group col-sm-3 {{ $errors->has('name') ? 'has-error' : '' }}">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
                @if($errors->has('name'))
                    <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>
            <div class="form-group col-sm-3">
                {!! Form::label('role_id', 'Role') !!}
                {!! Form::select('role_id', $roles, null, ['class' => 'form-control','id' => 'role_id']) !!}
            </div>
            <div class="form-group col-sm-3 {{ $errors->has('email') ? 'has-error' : '' }}">
                {!! Form::label('email', 'Email') !!}
                {!! Form::text('email', null, ['class' => 'form-control']) !!}
                @if($errors->has('email'))
                    <span class="help-block">{{ $errors->first('email') }}</span>
                @endif
            </div>
            <div class="form-group col-sm-3 {{ $errors->has('password') ? 'has-error' : '' }}">
                {!! Form::label('password', 'Password') !!}
                {!! Form::text('password', null, ['class' => 'form-control']) !!}
                @if($errors->has('password'))
                    <span class="help-block">{{ $errors->first('password') }}</span>
                @endif
            </div>
            <div class="form-group col-sm-12">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{!! route('admins.index') !!}" class="btn btn-default">Cancel</a>
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/user/edit.blade.php
@extends('admin.home')

@section('content_header')
    <div class="text-center">
        <label for="admin-users">Update Admin User</label>
    </div>
@stop

@section('content')
    @include('layouts.errors')
    <div class="panel-body">
        {!! Form::open(['route' => ['admins.update', $user->id], 'method' => 'put']) !!}
            <div class="form-group col-sm-3">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', $user->name, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group col-sm-3">
                {!! Form::label('role_id', 'Role') !!}
                {!! Form::select('role_id', $roles, $user->getRoleNames(), ['class' => 'form-control','id' => 'role_id']) !!}
            </div>
            <div class="form-group col-sm-3">
                {!! Form::label('email', 'Email') !!}
                {!! Form::text('email', $user->email, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group col-sm-3">
                {!! Form::label('password', 'Password') !!}
                {!! Form::text('password', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group col-sm-12">
                {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
            <a href="{!! route('admins.index') !!}" class="btn btn-default">Cancel</a>
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/user/index.blade.php
@extends('admin.home')

@section('content_header')
    <ol class="breadcrumb pull-right">
        <li class="breadcrumb-item"><a class="btn btn-primary" href="{!! route('admins.create') !!}" style="color:white">Add New</a></li>
    </ol>
    <br><br>
@stop

@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block" style="margin-top: 3%;">
            <button type="button" class="close" data-dismiss="alert">×</button>	
                <strong>{{ $message }}</strong>
        </div>
    @endif
    @if ($message = Session::get('danger'))
        <div class="alert alert-danger alert-block" style="margin-top: 3%;">
            <button type="button" class="close" data-dismiss="alert">×</button>	
                <strong>{{ $message }}</strong>
        </div>
    @endif
    <div class="panel panel-inverse" data-sortable-id="index-1">
        <div class="panel-heading">
            <label class="panel-title">&nbsp;Admins</label>
        </div>
        <div class="panel-body">
            <table class="table display table-striped table-bordered dt-responsive" >
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{!! $user->name !!}</td>
                            <td>
                                @if(!empty($user->getRoleNames()))
                                    @foreach($user->getRoleNames() as $role)
                                        @if($role == 'root-admin')
                                            <label class="badge btn-success">{!! $role !!}</label>
                                        @elseif ($role == 'admin')
                                            <label class="badge btn-primary">{!! $role !!}</label>
                                        @else 
                                            <label class="badge">{!! $role !!}</label>
                                        @endif
                                    @endforeach
                                @endif
                            </td>
                            <td>{!! $user->email !!}</td>
                            <td>
                                {!! Form::open(['route' => ['admins.destroy', $user->id], 'method' => 'DELETE', 'class' => 'form-delete']) !!}
                                    <div class="btn-group">
                                        <a href="{!! route('admins.show', [$user->id]) !!}" class='btn btn-success btn-xs'><i class="fa fa-eye"></i></a>
                                        <a href="{!! route('admins.edit', [$user->id]) !!}" class='btn btn-info btn-xs'><i class="fa fa-edit"></i></a>
                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                    </div>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="text-center">
        {!! $users->links() !!}
    </div>
@stop

resources/views/admin/user/show.blade.php
@extends('admin.home')

@section('content_header')

@stop

@section('content')
<div class="panel-body">
    <div class="col-sm-6">
        <table class="table table-striped table-bordered">
            <!-- Id Field -->
            <tr>
                <th>{!! Form::label('id', 'Id:') !!}</th>
                <td>{!! $user->id !!}</td>
            </tr>
            <!-- Name Field -->
            <tr>
                <th>{!! Form::label('name', 'Name:') !!}</th>
                <td>{!! $user->name !!}</td>
            </tr>
            <tr>
                <th>{!! Form::label('role_id', 'Role:') !!}</th>
                @foreach($user->getRoleNames() as $role)
                    <td><label class="badge">{!! $role !!}</label></td>
                @endforeach
            </tr>
            <tr>
                <th>{!! Form::label('email', 'Email') !!}</th>
                <td>{!! $user->email !!}</td>
            </tr>
        </table>
        <a href="{!! route('admins.index') !!}" class="btn btn-primary">Back</a>
    </div>
</div>
@stop